# Generated by Django 2.2.3 on 2019-07-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='money',
            new_name='user_money',
        ),
        migrations.RenameField(
            model_name='user_history',
            old_name='money',
            new_name='history_user_money',
        ),
    ]
