# Generated by Django 2.2.3 on 2019-07-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190730_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_history',
            old_name='history_user_money',
            new_name='user_history_money',
        ),
    ]
