# Generated by Django 2.2.3 on 2019-07-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190730_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='history',
        ),
        migrations.AddField(
            model_name='user_history',
            name='user_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User_account'),
        ),
    ]
