# Generated by Django 2.2.3 on 2019-08-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_group_account_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_account',
            old_name='user',
            new_name='use',
        ),
    ]
