# Generated by Django 2.2.3 on 2019-08-02 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190802_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_account',
            name='use',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
