# Generated by Django 2.2.3 on 2019-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190802_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_account',
            old_name='Group_money',
            new_name='group_money',
        ),
    ]
