# Generated by Django 2.2.4 on 2019-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190804_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_account',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
