# Generated by Django 2.2.4 on 2019-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20190804_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
