# Generated by Django 2.2.3 on 2019-08-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190805_1920'),
        ('mainapp', '0016_auto_20190805_1932'),
    ]

    operations = [
    ]
