# Generated by Django 2.2.3 on 2019-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_merge_20190805_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('send', models.CharField(max_length=100)),
                ('check', models.BooleanField(blank=True, null=True)),
                ('receive', models.CharField(max_length=100)),
            ],
        ),
    ]
