# Generated by Django 2.2.3 on 2019-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_account',
            name='group_money',
            field=models.IntegerField(default=0),
        ),
    ]
