# Generated by Django 2.2.3 on 2019-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20190805_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user_money',
            field=models.IntegerField(default=0),
        ),
    ]
