# Generated by Django 2.2.2 on 2019-08-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20190805_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm', models.BooleanField(blank=True, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Schedule')),
            ],
        ),
    ]
