# Generated by Django 2.2.2 on 2019-08-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_punish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punish',
            old_name='confirm',
            new_name='success',
        ),
    ]
