# Generated by Django 2.2.3 on 2019-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20190806_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='data published')),
                ('money', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
