# Generated by Django 2.2.3 on 2019-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_group_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_history',
            old_name='user',
            new_name='us',
        ),
    ]
