# Generated by Django 2.2.3 on 2019-08-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20190810_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_history',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Group_account'),
        ),
    ]
